### ISSUE TITLE
Function called outside component initialization after "npm run dev"

### ISSUE THREAD

**Issue by jonasXchen** [solana-developers/dapp-scaffold-svelte#8]
Error: Function called outside component initialization
    at get_current_component (/node_modules/svelte/internal/index.mjs:953:15)
    at Module.setContext (/node_modules/svelte/internal/index.mjs:985:5)
    at root.svelte:14:1
    at $$render (/node_modules/svelte/internal/index.mjs?v=b90a71ce:1770:22)
    at Object.render (/node_modules/svelte/internal/index.mjs?v=b90a71ce:1778:26)
    at render_response (file:///home/azureuser/projects/dapp-scaffold-svelte/.svelte-kit/runtime/server/index.js:1383:27)
    at async respond$1 (file:///home/azureuser/projects/dapp-scaffold-svelte/.svelte-kit/runtime/server/index.js:2996:4)
    at async resolve (file:///home/azureuser/projects/dapp-scaffold-svelte/.svelte-kit/runtime/server/index.js:3346:11)
    at async respond (file:///home/azureuser/projects/dapp-scaffold-svelte/.svelte-kit/runtime/server/index.js:3290:20)
    at async file:///home/azureuser/projects/dapp-scaffold-svelte/node_modules/@sveltejs/kit/dist/vite.js:2324:22

**Comment by silvestrevivo** [comment]
@jonasXchen please, can describe how do you get this error? It will be easier to scope the issue to be solved. Thanks!

**Comment by silvestrevivo** [comment]
Closing this issue since there is no more reports about it.
